---
- name: Install general packages for Magma
  apt:
    name: "{{ pkgGateway }}"
    state: present
    update_cache: yes
    
- name: Start resolvconf service
  systemd:
    state: started
    name: resolvconf

- name: Add dns entry to resolv.conf
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    line: "{{ item }}"
    create: yes
  loop: "{{ nameservers }}"
    
- name: Restart resolvconf service
  systemd:
    state: restarted
    name: resolvconf

- name: Update resolv.conf
  command: /usr/sbin/resolvconf -u