- name: copy inventory file
  copy:
    src: roles/magma-agw/files/99-magma.sh
    dest: "/etc/update-motd.d/99-magma"
    mode: '0777'

- name: Create cert directory
  ansible.builtin.file:
    path: '/var/opt/magma/tmp/certs'
    state: directory
    recurse: yes

- name: copy rootCA file
  copy:
    src: roles/magma-agw/files/rootCA.pem
    dest: "/var/opt/magma/tmp/certs/rootCA.pem"
    mode: '0777'
  register: rootCA_file

- name: Create Config directory
  ansible.builtin.file:
    path: '/var/opt/magma/configs'
    state: directory
    recurse: yes

- name: copy control_proxy file
  copy:
    src: roles/magma-agw/files/control_proxy.yaml
    dest: "/var/opt/magma/configs/control_proxy.yml"
    mode: '0777'
  register: control_proxy_file

- name: Stop magma services
  command: service magma@* stop
  when: control_proxy_file.changed or rootCA_file.changed or mConfigMCC.changed or mConfigMNC.changed or mConfigTAC.changed

- name: Start magma services
  systemd:
    name: magma@magmad
    state: started
  when: control_proxy_file.changed or rootCA_file.changed or mConfigMCC.changed or mConfigMNC.changed or mConfigTAC.changed
  