---
- name: replace eth1 in installation script
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX=""'
    line: GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"
  
- name: Change the interface
  shell: grub-mkconfig -o /boot/grub/grub.cfg

- name: Register default network interface name
  debug: 
    msg: "{{ ansible_default_ipv4.interface }}"
  register: default_nic

- name: Change the interface name
  ansible.builtin.replace:
    path: /etc/netplan/50-cloud-init.yaml
    regexp: "{{ default_nic.msg }}"
    replace: eth0

- name: Create interface directory
  ansible.builtin.file:
    path: '{{ INTERFACE_DIR }}'

- name: add couchbase.host to properties, works like add or replace
  lineinfile:
    path: /etc/network/interfaces
    regexp: 'source-directory {{ INTERFACE_DIR }}'
    line: "source-directory {{ INTERFACE_DIR }}"

- name: Create eth0 file. 
  copy:
    dest: "{{ INTERFACE_DIR }}/eth0"
    content: |
      auto eth0
        iface eth0 inet static
        address {{ eth0 }}
        netmask 255.255.252.0
        gateway 192.16.0.1
  register: network_changes_eth0

- name: Create eth1 file. 
  copy:
    dest: "{{ INTERFACE_DIR }}/eth1"
    content: |
      auto eth1
        iface eth1 inet static
        address {{ eth1 }}
        netmask 255.255.255.0
  register: network_changes_eth1

- name: Restart network service for interface eth0
  ansible.builtin.service:
    name: networking
    enabled: yes

- name: Remove netplan
  shell: apt-get --assume-yes purge nplan netplan.i

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: network_changes_eth0.changed or network_changes_eth1.changed

- name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: '{{ eth0 }}'
    search_regex: OpenSSH
    delay: 10
  vars:
    ansible_connection: local
  when: network_changes_eth0.changed or network_changes_eth1.changed