---
- name: start resolv.conf service
  systemd:
    state: started
    name: resolvconf

- name: add dns entry to resolv.conf
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    line: "{{ item }}"
    create: yes
  loop:
    - "nameserver 8.8.8.8"
    - "nameserver 8.8.4.4"
    - "nameserver 172.16.4.4"
    
- name: restart resolv.conf
  systemd:
    state: restarted
    name: resolvconf

- name: manually update resolv.conf
  command: /usr/sbin/resolvconf -u