---
- name: Copy upgrade file
  copy:
    src: roles/magma-agw/files/upgrade_agw.sh
    dest: "/root/upgrade_agw.sh"
    mode: '0777'
  register: upgrade_file
    
- name: Upgrade magma
  shell: "echo 'y'| /bin/bash /root/upgrade_agw.sh {{ magma5gVersion }}"
  when: magma5gVersion is defined
  register: upgradeShell

- local_action: command echo item
  with_items: upgradeShell.stdout_lines

- name: Upgrade magma
  shell: echo "y" | /bin/bash /root/upgrade_agw.sh
  when: magma5gVersion is not defined

- name: Disable stateless
  shell: magmad_cli.py config_stateless disable
  when: upgrade_file.changed

- name: Copy mme yml file
  copy:
    src: roles/magma-agw/files/mme.yml
    dest: "/var/opt/magma/configs/mme.yml"
  register: mme_yml_file

- name: Copy pipelined yml file
  copy:
    src: roles/magma-agw/files/pipelined.yml
    dest: "/var/opt/magma/configs/pipelined.yml"
  register: pipelined_yml_file

- name: Copy subscriberdb yml file
  copy:
    src: roles/magma-agw/files/subscriberdb.yml
    dest: "/var/opt/magma/configs/subscriberdb.yml"
  register: subscriberdb_yml_file

- name: Copy sessiond yml file
  copy:
    src: roles/magma-agw/files/sessiond.yml
    dest: "/var/opt/magma/configs/sessiond.yml"
  register: sessiond_yml_file

- name: Copy pipelined yml file to etc directory
  copy:
    src: roles/magma-agw/files/sessiond.yml
    dest: "/var/opt/magma/configs/sessiond.yml"
  register: sessiond_yml_file
  
- name: Stop magma services
  command: service magma@* stop
  when: mme_yml_file.changed or pipelined_yml_file.changed or subscriberdb_yml_file.changed or sessiond_yml_file.changed

- name: Start magma services
  systemd:
    name: magma@magmad
    state: started
  when: mme_yml_file.changed or pipelined_yml_file.changed or subscriberdb_yml_file.changed or sessiond_yml_file.changed