- name: Install AGW
  hosts: all
  become: yes
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: "../terraform/templates/agw_install_ubuntu.sh"
        dest: /root/agw_install_ubuntu.sh
        mode: 0777

    - name: start the installation script.
      shell: "echo 'y' | /bin/bash agw_install_ubuntu.sh {{ eth0 }}/24 192.16.0.1 {{ eth1 }}"
      ignore_unreachable: yes
      register: agw_install

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ eth0 }}'
        search_regex: OpenSSH
        delay: 10
      connection: local
      when: agw_install is changed

    - name: Wait until the file /tmp/foo is present before continuing
      wait_for:
        path: /tmp/agw_install_complete.txt
      register: install_complete

    - name: Reboot immediately if there was a change.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: install_complete is changed

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: '{{ eth0 }}'
        search_regex: OpenSSH
        delay: 10
      connection: local
      when: install_complete is changed