---
- name: Configure SSH keys 
  hosts: all
  become: yes
  tasks:
    - name: Configure ABot ssh keys on AGW
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ item }}"
      with_items:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD6ZZnqjVT+KH+jXioCKgTmWcUDl+HRaDN8u8x6cRfIEfnfFj+gUCqAoMSrOsEtPwWh0SrkB5IT2/tGwTcnYbW0apwxqDsbBxi9jO8+WQFwM8wFZCyBhIdMxQkfxohRt/zDg3Je00nOVJIQu84J4KIQYhkA3ygyyIiRUoDPF9NhPu0J22agusnAfS3QP8DWAlQRgC0xYV9OycUgCabB3U3FoTOY3He3Mcq0cH23zbbNvcS/A0pr0EDTfydTb0CoFLRV0NhQjn7doGjWdZt7OpxAFwNfdhxgHSn2H/j1TV283aL5Tk722FGKTOUHzqWREXQrrHOyTB0Ui9uqYTE/A0S/ abot@abot-magma-simulator-2"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWkin+2DjgbnWQ6jNPiRiq/Tae6oEa3QFSmfnvnymYsu4qYGyC33bWkHlvgCmiB7LADansAnShqy8luoyNuAERzsE9Yv3CHm5eQ/N/ROFM0iYlkSpCnY8x+Nbbh6ULjjDeFSfApPIRAsJLXRVu6DW4SBErxSjd69BmJwdAv0/P6sriEJvUSR3xZUY2CLbRG8kzGgOXhEychNdxxN15+KkEN+zelX7XM6sfmEcIRES4NpezOuWWrl4eDBJA8xSSYzdj9iACPx6edJbKen3QrF4muVreNpkd8rziEa0+lDMIK+kxu/ZIalgJCAyX0IiOXJJMiBCGiVWLk4J7dtbK78xv niteshkumar@nblap369"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKShaiuLqwREjDqyW0kCVsX3nO4+vwyHDtjslYHflYqn tapas.mishra@wavelabs.ai"

    - name: Retry until subscriber is not available 
      ansible.builtin.shell: subscriber_cli.py list
      register: result
      until: result.stdout.find("IMSI659050000000111") != -1
      retries: 50
      delay: 20

    - name: copy control_proxy file
      copy:
        src: roles/magma-agw/files/gateway_mconfig
        dest: "/etc/magma/gateway_mconfig"
        mode: '0644'
      register: gateway_mconfig_file

    - name: Stop magma services
      command: service magma@* stop
      when: gateway_mconfig_file.changed

    - name: Start magma services
      systemd:
        name: magma@magmad
        state: started
      when: gateway_mconfig_file.changed

    - name: Wait for MME PID 
      ansible.builtin.shell: pidof mme
      register: result
      until: result.stdout | length > 0
      retries: 50
      delay: 10