---
- name: Configure SSH keys 
  hosts: all
  become: yes
  tasks:
    - name: Configure ABot ssh keys on AGW
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ item }}"
      with_items:
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD6ZZnqjVT+KH+jXioCKgTmWcUDl+HRaDN8u8x6cRfIEfnfFj+gUCqAoMSrOsEtPwWh0SrkB5IT2/tGwTcnYbW0apwxqDsbBxi9jO8+WQFwM8wFZCyBhIdMxQkfxohRt/zDg3Je00nOVJIQu84J4KIQYhkA3ygyyIiRUoDPF9NhPu0J22agusnAfS3QP8DWAlQRgC0xYV9OycUgCabB3U3FoTOY3He3Mcq0cH23zbbNvcS/A0pr0EDTfydTb0CoFLRV0NhQjn7doGjWdZt7OpxAFwNfdhxgHSn2H/j1TV283aL5Tk722FGKTOUHzqWREXQrrHOyTB0Ui9uqYTE/A0S/ abot@abot-magma-simulator-2"
        - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDWkin+2DjgbnWQ6jNPiRiq/Tae6oEa3QFSmfnvnymYsu4qYGyC33bWkHlvgCmiB7LADansAnShqy8luoyNuAERzsE9Yv3CHm5eQ/N/ROFM0iYlkSpCnY8x+Nbbh6ULjjDeFSfApPIRAsJLXRVu6DW4SBErxSjd69BmJwdAv0/P6sriEJvUSR3xZUY2CLbRG8kzGgOXhEychNdxxN15+KkEN+zelX7XM6sfmEcIRES4NpezOuWWrl4eDBJA8xSSYzdj9iACPx6edJbKen3QrF4muVreNpkd8rziEa0+lDMIK+kxu/ZIalgJCAyX0IiOXJJMiBCGiVWLk4J7dtbK78xv niteshkumar@nblap369"
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKShaiuLqwREjDqyW0kCVsX3nO4+vwyHDtjslYHflYqn tapas.mishra@wavelabs.ai"

    # - name: Change the MCC value
    #   lineinfile:
    #     path: /etc/magma/gateway.mconfig
    #     search_string: '"mcc"'
    #     line: '      "mcc": "659",'
    #   register: mConfigMCC

    # - name: Change the MNC value
    #   lineinfile:
    #     path: /etc/magma/gateway.mconfig
    #     search_string: '"mnc"'
    #     line: '      "mnc": "05",'
    #   register: mConfigMNC

    # - name: Change the TAC value
    #   replace:
    #     path: /etc/magma/gateway.mconfig
    #     regexp: '"tac": 1,'
    #     after: '"mnc"'
    #     before: '"enableDnsCaching"'
    #     replace: '"tac": 11,'
    #   register: mConfigTAC

    - name: Retry until subscriber is not available 
      ansible.builtin.shell: subscriber_cli.py list
      register: result
      until: result.stdout.find("IMSI659050000000111") != -1
      retries: 50
      delay: 10
